### ISSUE TITLE
Unwanted card re render because of wrong equality checks on ComponentDidUpdate

### ISSUE THREAD

**Issue by picklecillo** [swaplet/react-native-swipe-cards-deck#18]
Hi. 
I've been having issues with cards re rendering and I noticed on ComponentDidUpdate, the way changes are being checked is wrong. 
```js
componentDidUpdate(prevProps, prevState) {
    if (prevProps.cards !== this.props.cards) { // <-- this
      ...
    }

    if (prevProps.actions !== this.props.actions) { // <-- and this
      ...
    }
  }
```
Since `cards` is most likely an array of objects, this kind of comparison (`prevProps.cards === this.props.cards`) does not work, as it will always be false.
![image](https://user-images.githubusercontent.com/3966092/125488600-294a88eb-9626-4861-8094-744eeebc8507.png)
The same goes for the `actions` object.

I will be giving [Lodash `_.isEqual`](https://lodash.com/docs/4.17.15#isEqual) a try.

Can anyone think of a different solution for this?
Thanks

**Comment by eyalabs** [comment]
Thank you for the issue. We are aware of the shallow equality for the cards. It is just how it was meant to be (and this is how it is with other, standard, even built-in, components).
The responsibility falls on the user to prevent the object (pointer) from changing whenever there is no real content change.

We can't solve it as you suggested because we can't know how deep the given object is, and this will have mysterious performance issues.

Take for example react's own [memo](https://reactjs.org/docs/react-api.html#reactmemo) component:

> By default it will only shallowly compare complex objects in the props object. If you want control over the comparison, you can also provide a custom comparison function as the second argument.

And after that there is this warning:

> This method only exists as a performance optimization. Do not rely on it to “prevent” a render, as this can lead to bugs.

That's why we don't have the option to change the way equality is done.

To solve this in your side of the code, I suggest you eliminate unnecessary object assigning and use `useMemo`/`useCallback` hooks in the code that loads your data.
