### ISSUE TITLE
Lag when handling swipe

### ISSUE THREAD

**Issue by JSDevelopment17** [swaplet/react-native-swipe-cards-deck#20]
Hello,
I'm finding that the card leaving the screen lags when I add a function call to the yup/nope actions.
I'm still using component based as we're on react navigation v4 still. I've tested this with a basic setState to true/false to ensure it's not my function being overly process heavy.
There's a good chance this is a problem in my code but wanted to query if it is a known bug?

`handleYup={this.handleYup.bind(this)}`

`handleYup (card) {
        try {
this.setState({ someVar: true })
            return true
        }
        catch (e) {
        }
      }`

**Comment by eyalabs** [comment]
There are no performance issues known on both platforms. It is very tricky in RN because it is hard to find the problem in these situations.
I suggest you make a new side project with the example code. then add similar yup/nope functions to see if it reacts the same. If there is still an issue in the new project, just post the code with a gif of the behavior that you are having and we will look at it. If there are no issues there then it is probably related to something else triggering re-renders.

**Comment by JSDevelopment17** [comment]
Thank you for your help. I have worked through this and you are correct that there was an unintended render as a result of a redux function. This has greatly improved the animation.
